---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  labels:
    app: fortune
    label: v1
spec:
  containers: 
  - name: fortune-container
    image: sohwy/myfortune:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000