---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  #namespace: nw
  labels:
    app: northwind
    label: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp-pod
  template:
    metadata:
      name: nwapp-pod
      labels:
        app: nwapp-pod
    spec:
      containers:
        - name: nwapp-container
          image: stackupiss/northwind-app:v2
          envFrom:
            - configMapRef:
                name: nwapp-cm
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nw-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: IfNotPresent
          ports:
            - name: nwapp-port
              containerPort: 3000